services:
  backend:
    build: ./backend
    container_name: debugsphere-api
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/debugsphere:/tmp/debugsphere
    restart: unless-stopped

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: debugsphere-worker
    command: node worker.js
    env_file:
      - ./backend/.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/debugsphere:/tmp/debugsphere
    restart: unless-stopped